#ifndef __APPLIER_H__
#define __APPLIER_H__

#include "pch.h"

#include <vector>

// Tracks every unit generated by the targeting system.
struct Applier
{
	Damage* damage;
	Status* status;

	bool success;

	Applier(Damage* damage = NULL, Status* status = NULL) 
		: damage(damage), status(status), success(false)
	{}

	void apply();

	~Applier() 
	{
		delete damage;
		//delete status; // Status are delete by being expired associated to their Effect
	}
};

#endif