#ifndef __PCH_H__
#define __PCH_H__

#include <iostream>

using namespace std;

enum ElementType { ELEMENT_NONE, ELEMENT_PHYSICAL, ELEMENT_FIRE, ELEMENT_WATER, ELEMENT_EARTH, ELEMENT_ICE, ELEMENT_LIGHTNING };
enum AbilityType { ABILITY_NONE, ABILITY_ATTACK_MELEE, ABILITY_ATTACK_RANGE, ABILITY_SPECIAL };
enum DamageType { DAMAGE_NONE, DAMAGE_PHYSICAL, DAMAGE_FIRE, DAMAGE_WATER, DAMAGE_EARTH, DAMAGE_ICE, DAMAGE_LIGHTNING, DAMAGE_HEALING };
enum StatusType { STATUS_NONE, STATUS_DAMAGE_PREVENTION, STATUS_DAMAGE_OVER_TIME, STATUS_TAUNT, STATUS_ATTACK_BONUS };
enum StatusBenefit { NEUTRAL, BUFF, DEBUFF };
enum TargetType { TARGET_RANDOM, TARGET_WEAKEST, TARGET_STRONGEST };

enum Skill { NO_SKILL, HUNDRED_BLADES, BLOCK, STRIKE, TAUNT, BATTLE_SHOUT, SHOOT, FOREWARN, SCOPE, TANGLE_TRAP };
#define NUMBER_OF_SKILLS 10

#endif
